version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo:/data/db

  backend:
    image: facestylizer/backend
    build: ./server
    depends_on:
      - mongo
    ports:
      - 8080:8080

  frontend:
    image: facestylizer/frontend
    build: ./client
    ports:
      - 3000:3000

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:password@mongo:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: root123 
      ME_CONFIG_BASICAUTH_PASSWORD: pass123 

volumes:
  mongo:
