name: jjgan
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - pillow
  - libjpeg-turbo
  - wandb
  - gdown
  - matplotlib
  - python=3.8
  - dlib
  - pytorch
  - scipy
  - tqdm
  - pip:
    - torchvision
    - fastapi[all]
    - fastapi-utilities
    - mangum
    - opencv-python-headless==4.5.3.56
