name: jjgan
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - pillow
  - dlib
  - libjpeg-turbo
  - opencv
  - wandb
  - gdown
  - matplotlib
  - python=3.8
  - pytorch
  - scipy
  - torchvision==0.12.0
  - tqdm
  - pip:
    - fastapi[all]
    - fastapi-utilities
